export const SPRITE = {
    NONE: 0,
    NOT_FOUND: 0,
    CLOCK: 1,
    CLOCK_ARROW: 2,
    LIGHT: 3,
    LAKE: 4,
    HUD: 5,
    PLAYER: 6,
    PLAYER_ARM_L: 7,
    PLAYER_ARM_R: 8,
    STONE_SWORD: 9,
    INV_STONE_SWORD: 10,
    STONE_PICK: 11,
    INV_STONE_PICK: 12,
    INV_STONE_AXE: 13,
    INV_WOOD_WALL: 14,
    INV_WORKBENCH: 15,
    WORKBENCH: 16,
    HEALTH_BAR_BG_COLOR: 17,
    HEALTH_BAR_BAR_BORDER: 18,
    HEALTH_BAR_BAR_COLOR: 19,
    SPINNER: 20,
    LEADERBOARD_BG: 21,
    SLOT: 22,
    FIRE_STICKS: 23,
    FIRE_BURN: 24,
    TREE: 25,
    DIAMOND: 26,
    STONE: 27,
    GOLD: 28,
    FOOT_L: 29,
    FOOT_R: 30,
    INV_SWORD_SLOT: 31,
    FLOWER0: 32,
    FLOWER1: 33,
    FLOWER2: 34,
    FLOWER3: 35,
    FLOWER4: 36,
    FLOWER5: 37,
    FLOWER6: 38,
    FLOWER7: 39,
    FLOWER8: 40,
    FLOWER9: 41,
    FLOWER10: 42,
    GRASS0: 43,
    GRASS1: 44,
    GRASS2: 45,
    GRASS3: 46,
    GRASS4: 47,
    GRASS5: 48,
    INV_SPEAR_SLOT: 49,
    SPEAR: 50,
    TORCH: 51,
    INV_TORCH: 52,
    WOLF: 53,
    HEALTH_BAR: 54,
    COLD_BAR: 55,
    FOOD_BAR: 56,
    WALL: 57,
    CAVE_STONE: 58,
    INV_WALL: 59,
    INV_STICKS: 60,
    INV_STONE: 61,
    INV_MEAT: 62,
    BUSH: 63,
    SAND: 64,
    AMYTHEST: 65,
    EMERALD: 66,
    APPLE: 67,
    INV_APPLE: 68,
    JOYSTICK_OUTER: 69,
    JOYSTICK_INNER: 70,
    INV_EMERALD: 71,
    INV_AMYTHYST: 72,
    INV_STONE_SHARD: 73,
    INV_DIAMOND: 74,
    RASBERRY_BUSH: 75,
    PLAYER_BODY_1: 76,
    WOOD_PICK: 77,
    INV_WOOD_PICK: 78,
    GOLD_PICK: 79,
    INV_GOLD_PICK: 80,
    DIAMOND_PICK: 81,
    INV_DIAMOND_PICK: 82,
    AMY_PICK: 83,
    INV_AMY_PICK: 84,
    WOOD_SWORD: 85,
    INV_WOOD_SWORD: 86,
    INV_CAMPFIRE: 87,
    GOLD_SWORD: 88,
    INV_GOLD_SWORD: 89,
    DIAMOND_SWORD: 90,
    INV_DIAMOND_SWORD: 91,
    AMYTHYST_SWORD: 92,
    INV_AMYTHYST_SWORD: 93,
    INV_GOLD: 94,
    DEATH_BOX: 95,
}

if (process.env.NODE_ENV === 'development') {
    function verifyObj(a: { [key: string]: number }) {
        let used = new Set();
        for (let l in a) {
            let val = a[l];
            if (val && used.has(val)) {
                throw `Packet did not pass verification key: ${l}, objj: ${a}`;
            }
            used.add(val);
        }
    }

    verifyObj(SPRITE);
}