name: Deploy Game Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Node & NPM
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install project npm dependancies on compiling server
              run: npm i

            - name: Build Game Server
              run: |
                  npm run build:server
                  cp package.json build/server
            - name: Copy executable to eu1 server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.EU1_HOST }}
                  username: ${{ secrets.EU1_USERNAME }}
                  password: ${{ secrets.EU1_PASSWORD }}
                  source: './build/server'
                  target: '/home/user/nodeapp'

            - name: Start eu1 game server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EU1_HOST }}
                  username: ${{ secrets.EU1_USERNAME }}
                  password: ${{ secrets.EU1_PASSWORD }}
                  script: |
                      source ~/.bashrc
                      cd /home/user/nodeapp/build/server/
                      cat ~/.env
                      cp ~/.env /home/user/nodeapp/build/server
                      nvm use 18
                      npm i forever -g
                      npm i
                      forever stopall
                      forever start server.js